apiVersion: eda.ansible.com/v1alpha1
kind: EDA
metadata:
  creationTimestamp: '2023-08-26T07:07:35Z'
  generation: 2
  labels:
    app.kubernetes.io/managed-by: eda-operator
    app.kubernetes.io/name: eda-dev
    app.kubernetes.io/operator-version: '2.4'
    app.kubernetes.io/part-of: eda-dev
  name: eda-dev
  namespace: aap
spec:
  route_tls_termination_mechanism: Edge
  ingress_type: Route
  loadbalancer_port: 80
  no_log: true
  image_pull_policy: IfNotPresent
  ui:
    replicas: 1
  set_self_labels: true
  api:
    gunicorn_workers: 2
    replicas: 1
  redis:
    replicas: 1
  automation_server_url: ''
  admin_user: admin
  loadbalancer_protocol: http
  worker:
    replicas: 1
...
