---
- name: Listen for ManagedCluster across
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: "cluster.open-cluster-management.io/v1"
        kind: ManagedCluster
        api_key: "{{ vault_api_key }}"
        label_selectors:
          - type=eda
  rules:
    - name: Start Managed Clusters Day2 Automation (Workflow Only)
      enabled: true
      condition:
        all:
          # Important: Do not add more than 2 (two) conditions to the list... it won't work!
          - event.type == "ADDED"
          - event.resource.status.conditions[0].status == "True" and
            event.resource.status.conditions[1].status == "True" and
            event.resource.status.conditions[2].status == "True" and
            event.resource.status.conditions[3].status == "True" and
            event.resource.status.conditions[4].status == "True"
      actions:
        - print_event:
            pretty: true
        - debug:
            msg: "Run Workflow DEBUG"
        - run_workflow_template:
            name: "Inventory Sync"
            organization: "acm-eda"
        - run_job_template:
            name: "Managed Clusters Day2 Automation"
            organization: "acm-eda"
            job_args:
              extra_vars:
                 namespace_to_add: "{{ event.resource.metadata.name }}-day2ops"
        - debug:
            msg: "Post Debug"
...
