---
- name: Listen for ConfigMaps across
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1
        kind: Namespace
        # api_key: "{{ vault_api_key }}"
        api_key: "eyJhbGciOiJSUzI1NiIsImtpZCI6ImhqMUR5S1l5WGF3ZHhibnN2ZkJ3RTJkVi1OMmw2UTdfbEdXWXNQR2xtbzgifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjIl0sImV4cCI6MTY5MzA0MTEzNiwiaWF0IjoxNjkzMDM3NTM2LCJpc3MiOiJodHRwczovL2t1YmVybmV0ZXMuZGVmYXVsdC5zdmMiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6ImFhcCIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJlZGEtazhzLXRlbXAiLCJ1aWQiOiI3MWI4ZmZlNS1kMzg4LTQwYjItOGRlMS1kOTE2NTk0ZGY3N2QifX0sIm5iZiI6MTY5MzAzNzUzNiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmFhcDplZGEtazhzLXRlbXAifQ.BPga42Aui1j1OLpEGHvEpZM1cucjw8CJ_H4yRFvVTOs08y69JAmIbCQkirmxiiLv_mvzgT6g7hXeyu35D-bP1htE_22keUvciRcW8g5k8QOHkPUd4xHA9qSSko5G5sZimlImx5VcGjn6vNLSPMgQlAfVYAV7uKsemBre4_Oz-zmrlGXoO5UKoWDbp2nnIsNtqXeasNFDgkhVKZM6ihvy1Cey408ZtrWBmaqJ415zFKi4EX5OiI6dzNPPQ-GS8F6aNf5a_w5tRKIGa4itdBvfZHcK1ZxTQ82AC0wkpLFM3PBkpMRWmN6kWz2pXsEjX4KR-kS5JEY4FW6rpl8n4GI8tdLJmPvgjJIy4SKPsPfJVcdGG8QGtIINMOpi9mVs7YzdGwEa7sjCPEvAKDk-e0oYWce0h3kIDjme_xr5VqAShtuQWm5agPdks_REZPBIqouPZSyBlgxPiy3WskVh2IHHdMpw800draNaOauTUtlCpmciED8jENejJJbmPiQxmm3HJqBTo-AuUoNGgtpdclW2pqm92nVjtJRwjwc784Ekj2G_FGJSwJZoW8fl8uoIDzE1ZnXfqyLfUfYnkjABJ0NmtGkyclRUiFMmF5OiyNLvtislW0mEt0gU70kdQz3A5RZud-ZCd1kC53EmLlmlMvcbMdWf5H0MARYdKga8bLVgTQ4"
  rules:
    - name: Print Add Events
      condition: event.type == "ADDED"
      action:
        debug:
          msg: "Test"
...
