---
- name: Listen for Namespaces across
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1
        kind: ManagedClusters
        api_key: "{{ vault_api_key }}"
        label_selectors:
          - type=eda
  rules:
    - name: Start Managed Clusters Day2 Automation
      condition: event.type == "ADDED"
      action:
        run_job_template:
          name: "Managed Clusters Day2 Automation"
          organization:	acm-eda

...
