---
- name: Listen for ManagedCluster across
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: "cluster.open-cluster-management.io/v1"
        kind: ManagedCluster
        api_key: "{{ vault_api_key }}"
        label_selectors:
          - type=eda
  rules:
    - name: Start Managed Clusters Day2 Automation
      condition:
        all:
          - event.type == "ADDED"
          - "event.resource.metadata.labels.feature.open-cluster-management.io/addon-managed-serviceaccount == available"
      actions:
        - print_event:
            pretty: true
        - debug:
            msg: "namespace_to_add: {{ event.resource.metadata.name }}-day2ops"
        - set_facts:
            fact:
              namespace_to_add: "{{ event.resource.metadata.name }}-day2ops"
#  ansible_rulebook.rule_set_runner - ERROR - Action run_workflow_template not supported
#        - run_workflow_template:
#            name: "Inventory Sync"
#            organization: "acm-eda"
        - run_job_template:
            name: "Managed Clusters Day2 Automation"
            organization: "acm-eda"
            job_args:
              extra_vars:
                 env: "{{ event.resource.metadata.env }}"

...
