---
- name: Listen for ConfigMaps across
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1
        kind: Namespace
        # api_key: "{{ vault_api_key }}"
        api_key: "eyJhbGciOiJSUzI1NiIsImtpZCI6ImhqMUR5S1l5WGF3ZHhibnN2ZkJ3RTJkVi1OMmw2UTdfbEdXWXNQR2xtbzgifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjIl0sImV4cCI6MTY5MzA0MTgxNywiaWF0IjoxNjkzMDM4MjE3LCJpc3MiOiJodHRwczovL2t1YmVybmV0ZXMuZGVmYXVsdC5zdmMiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6ImFhcCIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJlZGEtazhzLXRlbXAiLCJ1aWQiOiI3MWI4ZmZlNS1kMzg4LTQwYjItOGRlMS1kOTE2NTk0ZGY3N2QifX0sIm5iZiI6MTY5MzAzODIxNywic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmFhcDplZGEtazhzLXRlbXAifQ.XyHHnelEL1GtMBE8gAgb8dj3aDmlmhbPZeITOOGnnh154rnLk_zpFezI13CKfueDULWOPpOiQxED9hw_NHjKjbreLcAYD2uoJCc6ohZh1Ax8vUTiIf-yNCWgvoqXI8m5oMRDl-VGLmIFemC_cAVurmRA94d8osqfG77L3S5CEB2GraPXkrAJueUd2K16E6qpPsNGinxOpxHgbvNJMD7QuqX1mpgCF3yrkKdNtPj2MZJgtugSxdLPPMT9bzULpexCciMfiE3ptDdmK_3SKuclYg2LZE4l84L7u-NwPNdTVHX8Q3C0cLwvL-IjiQQsTkV-QP5g_fnEXA7cqicDss2moBw69jpnT5boeXq0r0rp65BzeaIAO8LZthEg6EhbK4bnb5Crox38bekr2-3W7MnfLmYq5clBhfGnn_TmBWeBxcJvspaUutB7JQwOCdcOobIvMdmPIWjUsFbWwrpmtEtGJTtYhhQ-qcuKoJU2caFwg5Ccwyt2gxMrl7iXNcgDa8FqJWUUjwufLlVzxBPxpIp8aZUptaAV5-8j5U2smFPdWq-8ikxRkxDFyovgrFaxY-ogslI5WRBebEAq2AU9KFqoa_tYbuebu_Dm9rJOenVgg3yr5-4H4hHPT2zYSuCT_6GA4dMAfCbD-6fLn6dyiK3k-bvCJr0O4irj_qUBhOWCpTI"
  rules:
    - name: Print Add Events
      condition: event.type == "ADDED"
      action:
        debug:
          msg: "Test"
...
