---
- name: Listen for ConfigMaps across
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1
        kind: ConfigMap
        # api_key: "{{ vault_api_key }}"
        api_key: "eyJhbGciOiJSUzI1NiIsImtpZCI6ImhqMUR5S1l5WGF3ZHhibnN2ZkJ3RTJkVi1OMmw2UTdfbEdXWXNQR2xtbzgifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjIl0sImV4cCI6MTY5MzAzOTQzMiwiaWF0IjoxNjkzMDM1ODMyLCJpc3MiOiJodHRwczovL2t1YmVybmV0ZXMuZGVmYXVsdC5zdmMiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6ImFhcCIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJlZGEtazhzLXRlbXAiLCJ1aWQiOiI3MWI4ZmZlNS1kMzg4LTQwYjItOGRlMS1kOTE2NTk0ZGY3N2QifX0sIm5iZiI6MTY5MzAzNTgzMiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmFhcDplZGEtazhzLXRlbXAifQ.Ilemgs5Qw8MafMHhBnv-5bNn1LnbX5Tpu3ehS35yOYRkyE2K0xSnK1FnvcvWJ_GRDmMvQ47Wakhs4aXKWnEEuDRJ2FeNwZArkQoqK-4rphYQWWUfLTVGHbo2D7LaEXnlmkJ-2kC3g5oglBiTgvucCxARSewg4Txm5CUu7ATeLjdkSE1VAw1mRZ_QR6DEqZJsnH_QZ2SxzX25VTlnSBs8HADZgqI5B0Fbf4rvZSIriF2tpjHXDmjqgvJfAeZlkLvOmCL1NzX7Mp0XIkbJ2K0EAz7Sah2K3mUi2BMKLp9J0OdNUPWdDgcywz3GR7ak9ZBHBXI_CAHCeFQwNBQ5g3XAsVaVJdpJfZTRkgUbkiA0DcfxrVJzQXpEfglnXMF8EKBalpHNTzDT_tZwWuG2k7solZC2Z5RXnRZShu-ffaOGL4ir-T38SCV-RxUwGFFHrwaTPjUOfPxQ7XbpUWDF0_S-v0KI8trvE7DIwVJ4VAuGOUJZgDx58tEOyC0D4zIsw8qh_u5o_jxTmUusKvBlIMo_gpxU9RZT3fdxwXanbaKpdcCg9GbqrIw_VXN0HbcdbXT-42qhhRywRPeQruQmxubAvPil0VHxklGdG84KjfYpANfLzA-2_Rbis1Xkd8H13wYS-6P1ZT0hw6dr87PTrKmlOcJDzdYdBmH8hvdeKSHRPsc"
  rules:
    - name: Print Add Events
      condition: event.type == "ADDED"
      action:
        debug:
          msg: "Test"
...
