---
- name: EDA Demo
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 5
  rules:
    - name: Controller Rule
      condition: event.i == 1
      action:
        run_job_template:
          name: "Managed Clusters Day2 Automation"
          organization: acm-eda
...
