---
- name: Listen for Namespaces across
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: "cluster.open-cluster-management.io/v1"
        kind: ManagedCluster
        api_key: "{{ vault_api_key }}"
        label_selectors:
          - type=eda
  rules:
    - name: Start Managed Clusters Day2 Automation
      condition: event.type == "ADDED"
      action:
        run_job_template:
          name: "Managed Clusters Day2 Automation"
          organization:	"acm-eda"
          job_args:
             extra_vars:
               namespace_to_add: "{{ event.resource.metadata.name }}-day2ops"
               env: "{{ event.resource.metadata.env }}"
               aap-day2-phase: "{{ event.resource.metadata.app-day2 }}"

...
