---
- name: Listen for ManagedCluster across
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: "cluster.open-cluster-management.io/v1"
        kind: ManagedCluster
        api_key: "{{ vault_api_key }}"
        label_selectors:
          - type=eda
  rules:
    - name: Start Managed Clusters Day2 Automation
      condition: event.type == "ADDED"
      actions:
        - print_event:
            pretty: true
        - debug:
            msg: "namespace_to_add: {{ event.resource.metadata.name }}-day2ops"
#        - run_workflow_template:
#            name: "Inventory Sync"
#            organization: "acm-eda"
        - run_job_template:
            name: "Managed Clusters Day2 Automation"
            organization: "acm-eda"
            job_args:
              extra_vars:
                env: "{{ event.resource.metadata.env }}"
...
