apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-mgmt
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: namespace-mgmt
subjects: # points to my ServiceAccount
- kind: ServiceAccount
  name: eda-k8s-temp
  namespace: aap
